### ISSUE TITLE
RCON tried to execute command that is not allowed

### ISSUE THREAD

**Issue by jp1995** [theY4Kman/bakkes-rcon#1]
I'm having some trouble using the request function to pass commands to bakkesmod.

Any command I try returns "ERR:illegal_command", despite working fine in bakkesmod console.

For example, sending gidekPlugin commands:
```
[17:05:47] [bakkesmod] > add_loss
[17:05:54] [bakkesmod] > add_win
[17:06:04] [bakkesmod] [class RCONPlugin] RCON tried to execute command that is not allowed (add_loss)!
[17:06:04] [bakkesmod] > sendback "ERR:illegal_command"
```

This is the code I'm using

```python
import asyncio
from bakkes_rcon import BakkesRconClient


async def main():
    async with BakkesRconClient(password="password") as client:
        cmd = await client.request(cmd="add_loss")
        print(cmd)


asyncio.run(main())
```

Am I doing something wrong?

**Comment by theY4Kman** [comment]
Wow, am I ridiculously late!

---

Yeah, the RCON plugin only allows commands explicitly whitelisted in `bakkesmod/data/rcon_commands.cfg` to be executed. Thankfully, though, it supports regular expressions, so if you don't care so much about security, and just want to run whatever through RCON, you can just add a line to `rcon_commands.cfg` with the pattern:
```regex
.*
```

Then, either restart the game, run `rcon_refresh_allowed` in the game console, or send `rcon_refresh_allowed` through RCON (because that command is whitelisted, by default).

ref: https://github.com/bakkesmodorg/BakkesMod2-Plugins/blob/728fe3974471f0af8f7d4fd102112f9421ea79aa/RCONPlugin/RCONPlugin.cpp#L249-L266
ref: https://github.com/bakkesmodorg/BakkesMod2-Plugins/blob/728fe3974471f0af8f7d4fd102112f9421ea79aa/RCONPlugin/RCONPlugin.cpp#L84-L117

---

I had plans to add explicit/implicit command whitelisting to the bakkes-rcon library, but never quite got there.
